steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tim-backend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/tim-backend:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/tim-backend']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tim-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tim-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60'

images:
  - 'gcr.io/$PROJECT_ID/tim-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/tim-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY

